version: 2.0
project_name: updatr
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd
    binary: updatr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
  