version: 2.0
project_name: updatr
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [ 'zip' ]
    files:
      - README.md
      - LICENSE
  